---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "media-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sonarr
        {{- include "media-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        env:
          - name: PGID
            value: "{{ .Values.global.pgid }}"
          - name: PUID
            value: "{{ .Values.global.puid }}"
        image: docker.io/linuxserver/sonarr
        imagePullPolicy: IfNotPresent
        ports:
          - name: sonarr
            containerPort: 8989
            protocol: TCP
        volumeMounts:
          - name: sonarr-config
            mountPath: /config
            #subPath: config/sonarr
      volumes:
        - name: sonarr-config
          hostPath:
            path: /mnt/media/vol2/config
---
### Service
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: sonarr
  selector:
    app: sonarr
---
### Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app: sonarr
    {{- include "media-server.labels" . | nindent 4}}
  {{- with .Values.sonarr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
  - host: {{ .Values.sonarr.ingress.suffix }}.{{ .Values.global.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
  tls:
    - hosts:
        - {{ .Values.sonarr.ingress.suffix }}.{{ .Values.global.host }}
      secretName: {{ .Values.sonarr.ingress.tls.secretName }}





