---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-media-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi
  iscsi:
    targetPortal: 10.23.1.6:3260
    iqn: iqn.2000-01.com.synology:NAS-01.Target-1.c258eab17c3
    lun: 1
    fsType: btrfs
    readOnly: false
