---
replicaCount: 1
DNS1:
  10.43.0.20
DNS2:
  10.43.0.20
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - pihole.phcristian.net
  path: "/admin"
  pathType: Prefix
  ingressClassName: traefik-internal
  tls:
    - secretName: pihole-certificate-secret
      hosts:
        - pihole.phcristian.net
  annotations:
    gethomepage.dev/description: Dynamically Detected Pihole
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: pihole.png
    gethomepage.dev/name: Pihole
serviceWeb:
  loadBalancerIP: 10.23.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 10.23.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDhcp:
  enabled: false
dnsmasq:
  customDnsEntries:
    - address=/nas-1.phcristian.net/10.23.1.6
    - address=/nas-2.phcristian.net/10.23.1.7
    - address=/homelab-0/10.23.1.2
    - address=/homelab-1/10.23.1.3
    - address=/homelab-2/10.23.1.4
