apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-media-server
  labels:
    app: plex-media-server
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: plex-media-server
    app.kubernetes.io/version: "1.41.3"
automountServiceAccountToken: false

