---
replicaCount: 1
DNS1:
  10.43.0.20
DNS2:
  10.43.0.20
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "pihole.home"
  path: "/admin"
  pathType: Prefix
  ingressClassName: nginx-internal
  annotations:
    gethomepage.dev/description: Dynamically Detected Pihole
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: pihole.png
    gethomepage.dev/name: Pihole
serviceWeb:
  loadBalancerIP: 10.23.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 10.23.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDhcp:
  enabled: false
