apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: pihole-ingress-certificate
  namespace: pihole-system
spec:
  secretName: pihole-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.phcristian.net
