global:
  host: phcristian.net
  puid: 1000
  pgid: 1000
  ingressClassName: traefik-internal

plex:
  claim: ""
  ingress:
    suffix: plex
    annotations: 
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: plex.png
      gethomepage.dev/name: Plex
    tls:
      secretName: plex-certificate-secret
  loadBalancerIP: 10.23.1.249

sonarr:
  ingress:
    suffix: sonarr
    annotations: 
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sonarr.png
      gethomepage.dev/name: Sonarr
    tls:
      secretName: sonarr-certificate-secret

radarr:
  ingress:
    suffix: radarr
    annotations: 
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: radarr.png
      gethomepage.dev/name: Radarr
    tls:
      secretName: radarr-certificate-secret
  loadBalancerIP: ""

prowlarr:
  ingress:
    suffix: prowlarr
    annotations: 
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: prowlarr.png
      gethomepage.dev/name: Prowlarr
    tls:
      secretName: prowlarr-certificate-secret

sabnzbd:
  ingress:
    suffix: sabnzbd
    annotations: 
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sabnzdb.png
      gethomepage.dev/name: Sabnzbd
    tls:
      secretName: sabnzbd-certificate-secret

