apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./metallb/pool.yaml
  - ./certmanager/cluster-issuer.yaml
  - ./pihole/pihole-certificate.yaml
  - ./longhorn/longhorn-certificate.yaml
