repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: csi-driver-nfs
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.0
    values:
      - ./values/longhorn.values.yaml

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.9

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.27.0
    values:
      - ./values/pihole.values.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/externaldns.values.yaml

  # Unbound
  - name: unbound
    namespace: pihole-system
    chart: ./manifests/unbound

# Ingress for local network
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    version: 34.4.0
    values:
      - ./values/traefik.values.yaml

  # Cert Manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.17.0
    values:
      - ./values/cert-manager.values.yaml

  # CSI NFS Driver
  - name: csi-driver
    namespace: csi-driver
    chart: csi-driver-nfs/csi-driver-nfs
    version: 4.9.0
