---
### StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-media-server
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  serviceName: plex-media-server
  selector:
    matchLabels:
      {{- include "media-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: plex-media-server
        {{- include "media-server.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: plex-media-server
      terminationGracePeriodSeconds: 120
      initContainers:
      containers:
      - name: {{ .Chart.Name }}
        image: docker.io/plexinc/pms-docker:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 32400
            path: "/web/index.html"
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 20
        livenessProbe:
          httpGet:
            port: 32400
            path: "/web/index.html"
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 20
        env:
          - name: ADVERTISE_IP
            value: http://{{ .Values.plex.loadBalancerIP }}:32400, https://{{ .Values.plex.ingress.suffix}}.{{ .Values.global.host }}
          - name: PGID
            value: "{{ .Values.global.pgid }}"
          - name: PUID
            value: "{{ .Values.global.puid }}"
          {{- if .Values.plex.claim }}
          - name: PLEX_CLAIM
            value: {{ .Values.plex.claim }}
          {{- end }}
        ports:
        - containerPort: 32400
          name: plex
        - containerPort: 8324
          name: plex-roku
        - containerPort: 32469
          name: plex-dlna
        - containerPort: 1900
          name: plex-upnp
          protocol: UDP
        - containerPort: 32410
          name: plex-gdm-1
          protocol: UDP
        - containerPort: 32412
          name: plex-gdm-2
          protocol: UDP
        - containerPort: 32413
          name: plex-gdm-3
          protocol: UDP
        - containerPort: 32414
          name: plex-gdm-4
          protocol: UDP          
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: config/plex
        - name: pms-transcode
          mountPath: /transcode
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true
        - name: media-volume-2
          mountPath: /data/vol2
        - name: media-volume-3
          mountPath: /data/vol3
        - name: media-volume-4
          mountPath: /data/vol4
        - name: media-volume-5
          mountPath: /data/vol5
      volumes:
      - name: pms-transcode
        emptyDir: {}
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-pvc
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: media-volume-2
        hostPath:
          path: /mnt/syno/vol2
      - name: media-volume-3
        hostPath:
          path: /mnt/syno/vol3
      - name: media-volume-4
        hostPath:
          path: /mnt/syno/vol4
      - name: media-volume-5
        hostPath:
          path: /mnt/syno/vol5
---
### Service
apiVersion: v1
kind: Service
metadata:
  name: plex-media-server-lb
  labels:
    app: plex-media-server
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.plex.loadBalancerIP }} 
  ports:
  - port: 32400
    targetPort: plex
    name: plex
  - port: 8324
    targetPort: plex-roku
    name: plex-roku
  - port: 32469
    targetPort: plex-dlna
    name: plex-dlna
  - port: 1900
    targetPort: plex-upnp
    name: plex-upnp
    protocol: UDP
  - port: 32410
    targetPort: plex-gdm-1
    name: plex-gdm-1
    protocol: UDP
  - port: 32412
    targetPort: plex-gdm-2
    name: plex-gdm-2
    protocol: UDP
  - port: 32413
    targetPort: plex-gdm-3
    name: plex-gdm-3
    protocol: UDP
  - port: 32414
    targetPort: plex-gdm-4
    name: plex-gdm-4
    protocol: UDP
  selector:
    app: plex-media-server
---
apiVersion: v1
kind: Service
metadata:
  name: plex-media-server
  labels:
    app: plex-media-server
    {{- include "media-server.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: plex
      name: plex
  selector:
    app: plex-media-server
---
### ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-media-server
  labels:
    app: plex-media-server
    {{- include "media-server.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
### Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-media-server-ingress
  labels:
    app: plex-media-server
    {{- include "media-server.labels" . | nindent 4}}
  {{- with .Values.plex.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
  - host: {{ .Values.plex.ingress.suffix }}.{{ .Values.global.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-media-server
            port:
              number: 32400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-media-server-ingress-route
  labels:
    app: plex-media-server
    {{- include "media-server.labels" . | nindent 4}}
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ .Values.plex.ingress.suffix }}.{{ .Values.global.host }}`)
    kind: Rule
    services:
    - name: plex-media-server
      port: 32400
  tls:
    secretName: {{ .Values.plex.ingress.tls.secretName }}
