---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: vol2-nfs-csi
#provisioner: nfs.csi.k8s.io
#parameters:
#  server: 10.23.1.6
#  share: /volume2/ph-vol2
#reclaimPolicy: Retain
#volumeBindingMode: Immediate
#mountOptions:
#  - hard
#  - nfsvers=4.1
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: vol2-pvc
#spec:
#  storageClassName: vol2-nfs-csi
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 3600Gi
#
